### ISSUE TITLE
@pika/react-dom/server not found

### ISSUE THREAD

**Issue by ije** [pikapkg/react#5]
hi, I try to import 'https://cdn.pika.dev/@pika/react-dom/server', but i got an error:
> Import 'https://cdn.pika.dev/-/@pika/react-dom@v16.13.1-OMAyhOHqrWQ0cTAAiQAz/dist=es2019,mode=exports/server' failed: 404 Not Found`

**Comment by jamesseanwright** [comment]
I'm seeing the same with `@sinon/fake-timers` when using Deno 1.0.2:

`error: Import 'https://cdn.pika.dev/-/@sinonjs/fake-timers@v6.0.1-JhTh9R3cBdH83IL6Lnpd/dist=es2019,mode=types/index.d.ts' failed: 404 Not Found`
